# KubeSphere: Projects(virl) > Storage > Persistent Volume Claims > Create 로 만들어도 된다.
# 계정당 스토리지는 512GB까지 할당된다.
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pixlate-data
  namespace: virl
spec:
  storageClassName: sandbox-container
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
